In [1]:
# NumPy - Array Manipulation.

In [2]:
import numpy as np

In [3]:
ar = np.random.randint(1,10,(3,4))

In [4]:
ar

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [6]:
ar.reshape(2,6)

array([[4, 4, 2, 4, 4, 4],
       [3, 5, 8, 7, 5, 3]])

In [8]:
ar.reshape(2,-24)

array([[4, 4, 2, 4, 4, 4],
       [3, 5, 8, 7, 5, 3]])

In [11]:
ar.T       # Transpose..rotate 180 degree

array([[4, 4, 8],
       [4, 4, 7],
       [2, 3, 5],
       [4, 5, 3]])

In [12]:
ar

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [13]:
ar.flatten()

array([4, 4, 2, 4, 4, 4, 3, 5, 8, 7, 5, 3])

In [14]:
ar1 = np.array([1,2,3,4,5])

In [15]:
ar1

array([1, 2, 3, 4, 5])

In [16]:
ar1.ndim

1

In [18]:
#np.expand_dims(ar1)
np.expand_dims(ar1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [19]:
np.expand_dims(ar1,axis=0)

array([[1, 2, 3, 4, 5]])

In [21]:
ar

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [23]:
np.squeeze(ar)    # it doesn't work here

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [27]:
data = np.array([[1],[2],[3]])   # squeeze only work in single elements 

In [25]:
data

array([[1],
       [2],
       [3]])

In [26]:
np.squeeze(data)

array([1, 2, 3])

In [28]:
ar1

array([1, 2, 3, 4, 5])

In [31]:
np.repeat(ar1 ,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [32]:
np.roll(ar1 ,2)

array([4, 5, 1, 2, 3])

In [33]:
ar1

array([1, 2, 3, 4, 5])

In [35]:
np.diag(ar1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [36]:
# Numpy - Binary Operatiors.

In [38]:
ar2 = np.random.randint(1,10,(3,4))

In [39]:
ar3 = np.random.randint(1,10,(3,4))

In [40]:
ar2

array([[9, 9, 9, 2],
       [3, 7, 9, 1],
       [8, 1, 6, 4]])

In [41]:
ar3

array([[1, 5, 3, 4],
       [7, 9, 1, 1],
       [6, 3, 7, 5]])

In [42]:
ar2 + ar3

array([[10, 14, 12,  6],
       [10, 16, 10,  2],
       [14,  4, 13,  9]])

In [43]:
ar2 - ar3

array([[ 8,  4,  6, -2],
       [-4, -2,  8,  0],
       [ 2, -2, -1, -1]])

In [44]:
ar2 * ar3

array([[ 9, 45, 27,  8],
       [21, 63,  9,  1],
       [48,  3, 42, 20]])

In [45]:
ar2 / ar3

array([[9.        , 1.8       , 3.        , 0.5       ],
       [0.42857143, 0.77777778, 9.        , 1.        ],
       [1.33333333, 0.33333333, 0.85714286, 0.8       ]])

In [46]:
ar2 % ar3

array([[0, 4, 0, 2],
       [3, 7, 0, 0],
       [2, 1, 6, 4]])

In [47]:
ar2 ** ar3

array([[       9,    59049,      729,       16],
       [    2187, 40353607,        9,        1],
       [  262144,        1,   279936,     1024]])

In [48]:
ar2 & ar3

array([[1, 1, 1, 0],
       [3, 1, 1, 1],
       [0, 1, 6, 4]])

In [49]:
ar2

array([[9, 9, 9, 2],
       [3, 7, 9, 1],
       [8, 1, 6, 4]])

In [50]:
ar3

array([[1, 5, 3, 4],
       [7, 9, 1, 1],
       [6, 3, 7, 5]])

In [51]:
-ar2

array([[-9, -9, -9, -2],
       [-3, -7, -9, -1],
       [-8, -1, -6, -4]])

In [52]:
ar2|ar3

array([[ 9, 13, 11,  6],
       [ 7, 15,  9,  1],
       [14,  3,  7,  5]])

In [53]:
ar2>ar3

array([[ True,  True,  True, False],
       [False, False,  True, False],
       [ True, False, False, False]])

In [54]:
# Numpy - String Functions.

In [55]:
ar4 = np.array(['soya','mahi'])

In [56]:
ar4

array(['soya', 'mahi'], dtype='<U4')

In [59]:
np.char.upper(ar4)

array(['SOYA', 'MAHI'], dtype='<U4')

In [60]:
np.char.title(ar4)

array(['Soya', 'Mahi'], dtype='<U4')

In [61]:
np.char.capitalize(ar4)

array(['Soya', 'Mahi'], dtype='<U4')

In [62]:
# Numpy - Mathematical Functions.

In [66]:
ar

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [67]:
np.sin(ar)

array([[-0.7568025 , -0.7568025 ,  0.90929743, -0.7568025 ],
       [-0.7568025 , -0.7568025 ,  0.14112001, -0.95892427],
       [ 0.98935825,  0.6569866 , -0.95892427,  0.14112001]])

In [68]:
np.cos(ar)

array([[-0.65364362, -0.65364362, -0.41614684, -0.65364362],
       [-0.65364362, -0.65364362, -0.9899925 ,  0.28366219],
       [-0.14550003,  0.75390225,  0.28366219, -0.9899925 ]])

In [74]:
np.tan(ar)

array([[ 1.15782128,  1.15782128, -2.18503986,  1.15782128],
       [ 1.15782128,  1.15782128, -0.14254654, -3.38051501],
       [-6.79971146,  0.87144798, -3.38051501, -0.14254654]])

In [79]:
np.tanh(ar)            # tangent

array([[0.9993293 , 0.9993293 , 0.96402758, 0.9993293 ],
       [0.9993293 , 0.9993293 , 0.99505475, 0.9999092 ],
       [0.99999977, 0.99999834, 0.9999092 , 0.99505475]])

In [76]:
np.log10(ar)

array([[0.60205999, 0.60205999, 0.30103   , 0.60205999],
       [0.60205999, 0.60205999, 0.47712125, 0.69897   ],
       [0.90308999, 0.84509804, 0.69897   , 0.47712125]])

In [78]:
np.exp(ar)           # Exponent     

array([[  54.59815003,   54.59815003,    7.3890561 ,   54.59815003],
       [  54.59815003,   54.59815003,   20.08553692,  148.4131591 ],
       [2980.95798704, 1096.63315843,  148.4131591 ,   20.08553692]])

In [81]:
np.sqrt(ar)          # square root

array([[2.        , 2.        , 1.41421356, 2.        ],
       [2.        , 2.        , 1.73205081, 2.23606798],
       [2.82842712, 2.64575131, 2.23606798, 1.73205081]])

In [83]:
np.power(ar , 2)      # power

array([[16, 16,  4, 16],
       [16, 16,  9, 25],
       [64, 49, 25,  9]])

In [84]:
np.mean(ar)

4.416666666666667

In [86]:
np.median(ar)

4.0

In [87]:
np.std(ar)            # standard deviation

1.6051133570215186

In [91]:
np.var(ar)             # varience

2.5763888888888893

In [92]:
ar         

array([[4, 4, 2, 4],
       [4, 4, 3, 5],
       [8, 7, 5, 3]])

In [93]:
np.max(ar)

8

In [94]:
np.min(ar)

2

In [95]:
# Sort, Search & Counting Functions.

In [97]:
import numpy as np

In [98]:
ar = np.array([2,3,4,4,3,5,6,7,4])

In [99]:
ar

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [100]:
np.sort(ar)

array([2, 3, 3, 4, 4, 4, 5, 6, 7])

In [101]:
np.searchsorted(ar, 11)

9

In [104]:
ar1 = np.array([0,23,56,34,0,0,0,])

In [105]:
np.count_nonzero(ar1)

3

In [106]:
ar

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [107]:
np.where(ar > 5)

(array([6, 7]),)

In [109]:
np.extract(ar>3 ,ar)

array([4, 4, 5, 6, 7, 4])

In [110]:
# Numpy - Byte Swapping.

In [111]:
ar

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [112]:
ar.byteswap()

array([144115188075855872, 216172782113783808, 288230376151711744,
       288230376151711744, 216172782113783808, 360287970189639680,
       432345564227567616, 504403158265495552, 288230376151711744])

In [113]:
# Numpy - Copies &Views.

In [114]:
ar

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [124]:
a = np.copy(ar)

In [118]:
b = ar.view()

In [126]:
b = ar

In [119]:
b

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [120]:
ar

array([2, 3, 4, 4, 3, 5, 6, 7, 4])

In [121]:
b[0] = 45

In [122]:
b

array([45,  3,  4,  4,  3,  5,  6,  7,  4])

In [123]:
ar

array([45,  3,  4,  4,  3,  5,  6,  7,  4])

In [127]:
# Numpy - Matrix Library.

In [128]:
import numpy.matlib as nm

In [129]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [130]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [131]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [132]:
# Numpy - Linear Algebra

In [133]:
ar1 = np.random.randint([[2,3],[4,5]])

In [134]:
ar2 = np.random.randint([[5,3],[2,5]])

In [135]:
np.dot(ar1,ar2)

array([[ 0,  0],
       [13, 19]])

In [136]:
ar1@ar2

array([[ 0,  0],
       [13, 19]])