In [1]:
# Create Array and Matrix

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]

In [ ]:
# convert list data into array
ar = np.array(l)

In [ ]:
ar

In [5]:
# convert list data into array
np.asarray(l)

array([1, 2, 3, 4])

In [6]:
type(ar)   

numpy.ndarray

In [7]:
a = [2,4,6]

In [8]:
# convert list data into array
np.asanyarray(a)

array([2, 4, 6])

In [9]:
ar1 = np.array([[1,2],[4,5]])

In [10]:
ar1

array([[1, 2],
       [4, 5]])

In [11]:
type(ar1)

numpy.ndarray

In [12]:
# Matrix is 2-d by default 
# it is subset of array

b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)   #it is subset of array

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
c[0]

1

In [20]:
c[0] = 100

In [21]:
c

array([100,   2,   3,   4])

In [22]:
a

array([100,   2,   3,   4])

In [23]:
# Copy Function
d = np.copy(a)

In [24]:
d

array([100,   2,   3,   4])

In [25]:
a[1] = 200

In [26]:
a

array([100, 200,   3,   4])

In [27]:
d

array([100,   2,   3,   4])

In [28]:
# fromfunction

np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [30]:
iterable = (i*i for i in range(5))

In [31]:
iterable

<generator object <genexpr> at 0x7f8adc4ca730>

In [32]:
# fromiter

np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
# fromstring....convert string to array

np.fromstring('345 243', sep=' ')

array([345., 243.])

In [34]:
np.fromstring('45 , 65' , sep=',')

array([45., 65.])

In [35]:
# Numpy - Data Types.

l = [2,3,4,6,8,5]

In [36]:
ar = np.array(l)

In [37]:
ar

array([2, 3, 4, 6, 8, 5])

In [38]:
# ndim..to know size and shape

ar.ndim

1

In [39]:
ar2 = np.array([[1,3,5,7],[3,6,8,4]])

In [40]:
ar2

array([[1, 3, 5, 7],
       [3, 6, 8, 4]])

In [41]:
ar2.ndim

2

In [42]:
ar2.size

8

In [43]:
ar2.shape

(2, 4)

In [44]:
ar2.dtype

dtype('int64')

In [47]:
ar22 = np.array([(1,4,45,45) , (23,34,45,67)])

In [48]:
ar22

array([[ 1,  4, 45, 45],
       [23, 34, 45, 67]])

In [49]:
ar22.dtype

dtype('int64')

In [50]:
range(5)

range(0, 5)

In [52]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
list(range(o,1,5))

In [55]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [56]:
list(np.arange(2.3,5.6))

[2.3, 3.3, 4.3, 5.3]

In [58]:
#np.linespace(1,5,10)
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
ar4 = np.zeros((3,4,2,3))
# it is a 4-d array

In [64]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [66]:
ar4.ndim

4

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
on = np.ones((2,3,2))

In [70]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [71]:
on *4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [75]:
np.empty((3,4))

array([[1., 1., 1., 2.],
       [2., 2., 1., 2.],
       [1., 2., 1., 2.]])

In [76]:
np.empty((3,5))

array([[4.63901736e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [77]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [83]:
np.logspace(2,5,10 , base = 2 )

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [85]:
# generate random data
arr = np.random.randn(3,4)

In [86]:
arr

array([[ 1.36304816,  0.45577163, -1.3352824 ,  2.8747199 ],
       [ 1.04111736,  0.0394258 , -1.68617608, -0.19149231],
       [-1.11587962,  0.07213224, -0.38621439, -0.2223991 ]])

In [88]:
import pandas as pd

In [89]:
pd.DataFrame(arr)

0         1         2         3
0  1.363048  0.455772 -1.335282  2.874720
1  1.041117  0.039426 -1.686176 -0.191492
2 -1.115880  0.072132 -0.386214 -0.222399

In [90]:
np.random.rand(3,4)    # produce random data

array([[0.41373954, 0.35823022, 0.57009144, 0.91669562],
       [0.14507202, 0.34898509, 0.8314383 , 0.99873074],
       [0.66541989, 0.71551213, 0.56797211, 0.26411903]])

In [92]:
np.random.randint(3,110,(3,4))  # produce integer

array([[ 95,  72, 100,  64],
       [106,  27, 106,  60],
       [ 90,  88,  25, 107]])

In [95]:
# we can also convert it into dataframe
pd.DataFrame(np.random.randint(3,110,(3,4)))

0    1   2    3
0  105   65  66   46
1   86   77  65  100
2   51  105  61   66

In [98]:
# store data in csv file
pd.DataFrame(np.random.randint(3,110,(3,4))).to_csv('test.csv')

In [104]:
ar2 = np.random.rand(3,4)

In [105]:
ar2

array([[0.21388592, 0.15631284, 0.72397158, 0.61746652],
       [0.35656999, 0.11524702, 0.94533834, 0.89985089],
       [0.38684382, 0.54848043, 0.13284138, 0.83151604]])

In [106]:
ar3 = ar2.reshape(6,-1)

In [107]:
ar3

array([[0.21388592, 0.15631284],
       [0.72397158, 0.61746652],
       [0.35656999, 0.11524702],
       [0.94533834, 0.89985089],
       [0.38684382, 0.54848043],
       [0.13284138, 0.83151604]])

In [108]:
ar3[1][1]

0.6174665166131087

In [109]:
ar3[2:5]

array([[0.35656999, 0.11524702],
       [0.94533834, 0.89985089],
       [0.38684382, 0.54848043]])

In [110]:
ar3[2:5,1]

array([0.11524702, 0.89985089, 0.54848043])

In [111]:
ar4 = np.random.randint(1,100,(5,5))

In [112]:
ar4

array([[54, 50, 94, 22,  3],
       [15, 82, 15,  7,  6],
       [78, 52, 85, 45,  2],
       [81, 28, 94, 81, 32],
       [78, 85, 55, 81, 81]])

In [113]:
ar4>50

array([[ True, False,  True, False, False],
       [False,  True, False, False, False],
       [ True,  True,  True, False, False],
       [ True, False,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [115]:
ar4[ar4>50]

array([54, 94, 82, 78, 52, 85, 81, 94, 81, 78, 85, 55, 81, 81])

In [116]:
ar4

array([[54, 50, 94, 22,  3],
       [15, 82, 15,  7,  6],
       [78, 52, 85, 45,  2],
       [81, 28, 94, 81, 32],
       [78, 85, 55, 81, 81]])

In [117]:
ar4[2:4, [1,2]]

array([[52, 85],
       [28, 94]])

In [118]:
ar4[0][0] = 500

In [119]:
ar4

array([[500,  50,  94,  22,   3],
       [ 15,  82,  15,   7,   6],
       [ 78,  52,  85,  45,   2],
       [ 81,  28,  94,  81,  32],
       [ 78,  85,  55,  81,  81]])

In [120]:
ar5 = np.random.randint(1,3 ,(3,3))
ar6 = np.random.randint(1,3 ,(3,3))

In [121]:
ar5

array([[2, 1, 2],
       [1, 2, 2],
       [2, 2, 2]])

In [122]:
ar6

array([[1, 1, 1],
       [1, 2, 2],
       [2, 1, 1]])

In [123]:
ar5+ar6

array([[3, 2, 3],
       [2, 4, 4],
       [4, 3, 3]])

In [124]:
ar5-ar6

array([[1, 0, 1],
       [0, 0, 0],
       [0, 1, 1]])

In [125]:
ar5/ar6

array([[2., 1., 2.],
       [1., 1., 1.],
       [1., 2., 2.]])

In [126]:
ar5*ar6

array([[2, 1, 2],
       [1, 4, 4],
       [4, 2, 2]])

In [128]:
ar5@ar6            # index by multiplication

array([[7, 6, 6],
       [7, 7, 7],
       [8, 8, 8]])

In [129]:
ar5/0

/tmp/ipykernel_182/4261370027.py:1: RuntimeWarning: divide by zero encountered in divide
  ar5/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [130]:
ar5 +100

array([[102, 101, 102],
       [101, 102, 102],
       [102, 102, 102]])

In [131]:
ar5 **2

array([[4, 1, 4],
       [1, 4, 4],
       [4, 4, 4]])

In [132]:
# Numpy -Broadcasting

In [134]:
ar = np.zeros((4,4))

In [135]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [136]:
row = np.array([1,2,3,4])

In [137]:
row

array([1, 2, 3, 4])

In [139]:
row.ndim

1

In [140]:
row.shape

(4,)

In [138]:
ar + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [141]:
row.T

array([1, 2, 3, 4])

In [144]:
col = np.array([[1,2,3,4]])

In [145]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [146]:
col.T + ar

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [148]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [149]:
ar2 = np.random.randint(1,4,(3,4))

In [150]:
ar2

array([[2, 1, 2, 1],
       [1, 3, 2, 2],
       [2, 2, 1, 1]])

In [152]:
ar2.dtype

dtype('int64')

In [154]:
np.sqrt(ar2)

array([[1.41421356, 1.        , 1.41421356, 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        , 1.        ]])

In [155]:
np.exp(ar2)

array([[ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 ,  7.3890561 ],
       [ 7.3890561 ,  7.3890561 ,  2.71828183,  2.71828183]])

In [156]:
np.log10(ar2)

array([[0.30103   , 0.        , 0.30103   , 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.30103   ],
       [0.30103   , 0.30103   , 0.        , 0.        ]])