# PCA Implementation

In [26]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import decomposition 
from sklearn.decomposition import PCA
from sklearn import datasets

# Import for doing 3-d projections with matplotlib < 3.2
import mpl_toolkits.mplot3d 

In [27]:
import pandas as pd
df=pd.read_csv('1.0-winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [28]:
df.keys()

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [29]:
## Standardization

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [30]:
scaler.fit(df)

StandardScaler()

In [31]:
scaled_data = scaler.transform(df)
scaled_data

array([[-0.52835961,  0.96187667, -1.39147228, ..., -0.57920652,
        -0.96024611, -0.78782264],
       [-0.29854743,  1.96744245, -1.39147228, ...,  0.1289504 ,
        -0.58477711, -0.78782264],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.04808883,
        -0.58477711, -0.78782264],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.54204194,
         0.54162988,  0.45084835],
       [-1.39015528,  0.65462046, -0.77526673, ...,  0.30598963,
        -0.20930812, -0.78782264],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.01092425,
         0.54162988,  0.45084835]])

In [32]:
## Applying PCA Algorithm
pca = PCA(n_components=2)

In [33]:
data_pca=pca.fit_transform(scaled_data)

In [34]:
data_pca


array([[-1.77944158,  1.15730315],
       [-1.00418467,  2.07183784],
       [-0.91578319,  1.3934342 ],
       ...,
       [-1.36626511, -0.51756099],
       [-2.36714672,  0.70354479],
       [-0.28877628, -1.24084585]])

In [35]:
pca.explained_variance_

array([3.12312087, 2.24328497])